### ISSUE TITLE
port to Go

### ISSUE THREAD

**Issue by chadwhitacre** [badges/img.shields.io-old#2]
Per https://www.youtube.com/watch?v=hkgiWh-at1M#t=57m04s, we're going to look at porting this API server to Go. The shields.io server will be in Rails.

**Comment by chadwhitacre** [comment]
@nathany reminds on [Twitter](https://twitter.com/nathany/status/401490313211953152) that we should make sure https://github.com/jbowes/buckler doesn't already fit the bill.

**Comment by chadwhitacre** [comment]
That's the Go CLI, @olivierlacan, per https://github.com/gittip/shields.io/issues/47. @jbowes also wrapped it as a web service. Maybe this is going to be easier than we thought? :-)

**Comment by nathany** [comment]
Indeed, we should be able to adopt @jbowes MIT/Apache licensed code as the official image server/API and _Go_ from there. HTTPS, Retina, API docs...

If @jbowes is willing to move his repo under gittip, perhaps that would be a better place to further discuss what's next?

**Comment by chadwhitacre** [comment]
Sounds good to me. We would need to discuss the URL layout and the plugin architecture.

**Comment by chadwhitacre** [comment]
I've reached out on [Twitter](https://twitter.com/whit537/status/403347054228828160).

**Comment by chadwhitacre** [comment]
Closing in favor of https://github.com/gittip/shields.io/issues/84.
